{
 "title": "Gold Monitor",
 "description": "Displays all important metrics from your Gold farming node and all connected harvesters, collected by gold-monitor.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "Pool",
    "query": {
     "query": "label_values(gold_current_pool_points, url)"
    }
   },
   {
    "name": "PlotType",
    "query": {
     "query": "label_values(gold_plot_count, type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sync Status",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gold_sync_status" }
   ]
  },
  {
   "title": "Plot Size Delta",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(gold_plot_size{type=\"$PlotType\"})"
    }
   ]
  },
  {
   "title": "Plot Count Delta",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "plots" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(gold_plot_count{type=\"$PlotType\"})"
    }
   ]
  },
  {
   "title": "Total Farmed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "GL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gold_farmed_total_mojos/1e12", "legendFormat": "Difficulty" }
   ]
  },
  {
   "title": "Total Balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "GL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gold_confirmed_total_mojos/1e12",
     "legendFormat": "Difficulty"
    }
   ]
  },
  {
   "title": "Points Success Rate 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gold_pool_points_acknowledged_24h{url=\"$Pool\"} / gold_pool_points_found_24h{url=\"$Pool\"}",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Full Node Peers",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gold_connections_count{type=\"Full Node\"}"
    }
   ]
  },
  {
   "title": "Farmer Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gold_connections_count{type=\"Farmer\"}"
    }
   ]
  },
  {
   "title": "Harvester Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gold_connections_count{type=\"Harvester\"}"
    }
   ]
  },
  {
   "title": "Plot Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gold_plot_size{type=\"$PlotType\"})",
     "legendFormat": "Plot Size"
    }
   ]
  },
  {
   "title": "Plot Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "plots" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gold_plot_count{type=\"$PlotType\"})",
     "legendFormat": "Plot Count"
    }
   ]
  },
  {
   "title": "Expected Time To Win",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "18.75 / (sum(gold_plot_size) / sum(gold_network_space))"
    }
   ]
  },
  {
   "title": "Points Found 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "points" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gold_pool_points_found_24h{url=\"$Pool\"}",
     "legendFormat": "Points"
    }
   ]
  },
  {
   "title": "gold Network Space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gold_network_space", "legendFormat": "Netspace" }
   ]
  },
  {
   "title": "Points Acknowledged 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "points" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gold_pool_points_acknowledged_24h{url=\"$Pool\"}",
     "legendFormat": "Points"
    }
   ]
  },
  {
   "title": "Signage Points",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gold_signage_points_total[5m]) * 60",
     "legendFormat": "Challanges"
    }
   ]
  },
  {
   "title": "Plot Size Per Harvester",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gold_plot_size{type=\"$PlotType\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Peak Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gold_peak_height", "legendFormat": "Difficulty" }
   ]
  },
  {
   "title": "Farming Difficulty",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gold_diffculty", "legendFormat": "Difficulty" }
   ]
  },
  {
   "title": "Proofs Found",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "proof" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(increase(gold_proofs_found_total[10y]))",
     "legendFormat": "Difficulty"
    }
   ]
  },
  {
   "title": "Current Points",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gold_current_pool_points{url=\"$Pool\"}",
     "legendFormat": "Difficulty"
    }
   ]
  },
  {
   "title": "Pool Difficulty",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gold_current_pool_difficulty{url=\"$Pool\"}",
     "legendFormat": "Difficulty"
    }
   ]
  },
  {
   "title": "Pool Errors 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gold_num_pool_errors_24h{url=\"$Pool\"}"
    }
   ]
  },
  {
   "title": "Filters Passed",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gold_plots_passed_filter_total[5m]) * 60",
     "legendFormat": "Filters Passed"
    }
   ]
  },
  {
   "title": "Challenges",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gold_block_challenges_total[5m]) * 60",
     "legendFormat": "Challanges"
    }
   ]
  },
  {
   "title": "Plot Count Per Harvester",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "plots" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gold_plot_count{type=\"$PlotType\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(avg_over_time(gold_mempool_size[5m]))",
     "legendFormat": "Mempool Size"
    }
   ]
  },
  {
   "title": "GL Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gold_price_usd_cent/100", "legendFormat": "Difficulty" }
   ]
  },
  {
   "title": "Total Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gold_price_usd_cent/100 * gold_confirmed_total_mojos/1e12",
     "legendFormat": "Difficulty"
    }
   ]
  },
  {
   "title": "Proofs Found",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gold_proofs_found_total[5m]) * 60",
     "legendFormat": "Proofs"
    }
   ]
  },
  {
   "title": "Harvester Lookup Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gold_lookup_time_seconds_sum[5m])) / sum(rate(gold_lookup_time_seconds_count[1m]))",
     "legendFormat": "Average"
    },
    {
     "expr": "histogram_quantile(1., sum(rate(gold_lookup_time_seconds_bucket[1m])) by (le))",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}